from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import yaml

_HERE = Path(__file__).resolve().parent

SOURCE_CSV = _HERE.parent / "data" / "reference" / "npci-declines.csv"
OUTPUT_YAML = _HERE / "issuers.yaml"

SOURCE_NAME = "NPCI NFS/AEPS product-wise declines"
SOURCE_URL = "https://dataful.in/datasets/336/"

PRODUCTS: tuple[str, ...] = ("NFS",)
TOP_N = 8
CLOSURE_TOLERANCE_PCT = 1.0


def observation_months(frame: pd.DataFrame) -> pd.Series:
    """Decode the year-and-month-in-the-day-slot column into real months."""
    stamps = pd.to_datetime(frame["date"])
    if not (stamps.dt.month == 1).all():
        raise ValueError(
            "expected every date to carry month 01 with the real month in the "
            "day slot; this file does not match that shape, so decoding it "
            "would silently pick the wrong month"
        )
    if not stamps.dt.day.between(1, 12).all():
        raise ValueError("day slot outside 1-12, so it cannot be a month number")
    return pd.PeriodIndex.from_fields(
        year=stamps.dt.year, month=stamps.dt.day, freq="M"
    ).to_series(index=frame.index)


def _normalised_key(names: pd.Series) -> pd.Series:
    """Collapse 'Union Bank Of India' and 'Union Bank of India' onto one bank."""
    return names.str.strip().str.replace(r"\s+", " ", regex=True).str.casefold()


def select_issuers(
    frame: pd.DataFrame, products: tuple[str, ...], top_n: int
) -> tuple[pd.DataFrame, str]:
    """The ``top_n`` largest issuers in the most recent month, rates volume-weighted."""
    missing = set(products) - set(frame["product"].unique())
    if missing:
        raise ValueError(
            f"products {sorted(missing)} are not in this file; it contains "
            f"{sorted(frame['product'].unique())}"
        )

    frame = frame.assign(month=observation_months(frame))
    latest = frame["month"].max()
    rows = frame.loc[(frame["month"] == latest) & frame["product"].isin(products)].copy()

    closure = (
        rows["approved_transaction_volume"]
        + rows["business_decline_transactions"]
        + rows["technical_decline_transactions"]
    )
    unclosed = rows.loc[(closure - 100.0).abs() > CLOSURE_TOLERANCE_PCT]
    if not unclosed.empty:
        print(
            f"  warning: {len(unclosed)} of {len(rows)} rows in {latest} do not sum "
            f"to 100% across approved/BD/TD and are excluded",
            file=sys.stderr,
        )
        rows = rows.drop(unclosed.index)

    rows["key"] = _normalised_key(rows["issuer_bank"])
    rows["td_volume"] = rows["technical_decline_transactions"] * rows["total_volume"]

    grouped = rows.groupby("key").agg(
        name=("issuer_bank", "first"),
        volume=("total_volume", "sum"),
        td_volume=("td_volume", "sum"),
    )
    selected = grouped.nlargest(top_n, "volume").copy()
    if len(selected) < top_n:
        raise ValueError(f"only {len(selected)} issuers available, need {top_n}")

    selected["td_rate"] = (selected["td_volume"] / selected["volume"] / 100).round(6)

    # Shares are carried as integer millionths so the rounded values sum to
    # exactly 1.0; generate.py rejects a table that does not.
    micros = (selected["volume"] / selected["volume"].sum() * 1_000_000).round().astype(int)
    micros.iloc[0] += 1_000_000 - int(micros.sum())
    selected["volume_share"] = micros / 1_000_000

    return selected.reset_index(drop=True), str(latest)


def write_yaml(selected: pd.DataFrame, month: str, products: tuple[str, ...]) -> None:
    body = yaml.safe_dump(
        [
            {
                "name": row["name"],
                "volume_share": float(row["volume_share"]),
                "td_rate": float(row["td_rate"]),
            }
            for _, row in selected.iterrows()
        ],
        sort_keys=False,
    )
    header = "\n".join(
        [
            f"# Generated by generator/build_issuers.py from {SOURCE_CSV.name} —"
            " do not edit by hand.",
            f"# Source: {SOURCE_NAME}",
            f"# URL: {SOURCE_URL}",
            f"# Month: {month}   Product(s): {', '.join(products)}"
            f"   Top {len(selected)} issuers by volume.",
            "#",
            "# Used for relative issuer dispersion only, not as UPI Autopay rates.",
            "# NFS is ATM interchange; the simulator models UPI Autopay, cards and",
            "# NACH. What generate.py takes from this table is which banks are worse",
            "# on technical declines relative to their peers — a property of issuer",
            "# infrastructure, not of the rail these numbers were measured on.",
            "#",
            "# volume_share: share of the top-N volume, normalised to sum to 1.0",
            "# td_rate: technical decline share, as a decimal",
            "",
        ]
    )
    OUTPUT_YAML.write_text(header + body)


def main() -> None:
    frame = pd.read_csv(SOURCE_CSV)
    selected, month = select_issuers(frame, PRODUCTS, TOP_N)
    write_yaml(selected, month, PRODUCTS)

    weighted_td = float((selected["volume_share"] * selected["td_rate"]).sum())
    td_spread = selected["td_rate"].max() / selected["td_rate"].min()

    print(f"source   {SOURCE_CSV}")
    print(f"month    {month}   product(s) {', '.join(PRODUCTS)}   top {TOP_N} by volume")
    print(f"\n  {'issuer':<34}{'vol (mn)':>10}{'share':>9}{'td_rate':>10}")
    print("  " + "-" * 63)
    for _, row in selected.iterrows():
        print(
            f"  {row['name']:<34}{row['volume']:>10.2f}{row['volume_share']:>9.4f}"
            f"{row['td_rate']:>10.4f}"
        )
    print("  " + "-" * 63)
    print(
        f"  {'volume-weighted':<34}{selected['volume'].sum():>10.2f}"
        f"{selected['volume_share'].sum():>9.4f}{weighted_td:>10.4f}"
    )
    print(f"\n  td_rate spread (max/min): {td_spread:.2f}x")
    print(f"\nwrote {OUTPUT_YAML}")


if __name__ == "__main__":
    main()
